CREATE TABLE
    IF NOT EXISTS customers (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        customer_no VARCHAR(30) NOT NULL UNIQUE,
        first_name VARCHAR(100) NOT NULL,
        last_name VARCHAR(100),
        father_name VARCHAR(150),
        mother_name VARCHAR(150),
        mobile VARCHAR(20) NOT NULL,
        alternate_mobile VARCHAR(20),
        aadhaar_no VARCHAR(12) UNIQUE,
        pan_no VARCHAR(10) UNIQUE,
        dob DATE,
        gender ENUM ('male', 'female', 'other'),
        occupation VARCHAR(100),
        monthly_income DECIMAL(12, 2) DEFAULT 0.00,
        address TEXT,
        city VARCHAR(100),
        district VARCHAR(100),
        state VARCHAR(100),
        pincode VARCHAR(10),
        photo VARCHAR(255),
        reference_name VARCHAR(150),
        reference_mobile VARCHAR(20),
        remarks TEXT,
        status ENUM ('active', 'inactive', 'blocked') DEFAULT 'active',
        created_by BIGINT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        CONSTRAINT fk_customers_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
        UNIQUE KEY unique_customer_no (customer_no),
        UNIQUE KEY unique_mobile (mobile),
        UNIQUE KEY unique_aadhaar_no (aadhaar_no),
        UNIQUE KEY unique_pan_no (pan_no),
        INDEX idx_customer_no (customer_no),
        INDEX idx_mobile (mobile),
        INDEX idx_name (first_name, last_name),
        INDEX idx_status (status)
    );